# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 12:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, null=True)),
                ('creation_name', models.CharField(blank=True, max_length=256, null=True)),
                ('pay_per_name', models.CharField(blank=True, max_length=256, null=True)),
                ('one_liner', models.CharField(blank=True, max_length=512, null=True)),
                ('main_video_embed', models.URLField(blank=True, max_length=2048, null=True)),
                ('main_video_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('image_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('image_small_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('thanks_video_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('thanks_embed', models.URLField(blank=True, max_length=2048, null=True)),
                ('thanks_message', models.TextField(blank=True, max_length=2048, null=True)),
                ('is_monthly', models.BooleanField(default=False)),
                ('has_rss', models.BooleanField(default=False)),
                ('has_sent_rss_notify', models.BooleanField(default=False)),
                ('rss_feed_title', models.CharField(blank=True, max_length=1024, null=True)),
                ('rss_artwork_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('is_charged_immediately', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pledge_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('patron_count', models.IntegerField(blank=True, null=True)),
                ('discord_server_id', models.CharField(blank=True, max_length=512, null=True)),
                ('google_analytics_id', models.CharField(blank=True, max_length=512, null=True)),
                ('earnings_visibility', models.CharField(blank=True, choices=[('private', 'private'), ('public', 'public'), ('patrons_only', 'patrons_only')], max_length=100, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
