# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-17 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patron_status', models.CharField(blank=True, choices=[('active_patron', 'active_patron'), ('declined_patron', 'declined_patron'), ('former_patron', 'former_patron')], max_length=256, null=True)),
                ('is_follower', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('pledge_relationship_start', models.DateTimeField(blank=True, null=True)),
                ('lifetime_support_cents', models.IntegerField(default=0)),
                ('currently_entitled_amount_cents', models.IntegerField()),
                ('last_charge_date', models.DateTimeField(blank=True, null=True)),
                ('last_charge_status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Declined', 'Declined'), ('Deleted', 'Deleted'), ('Pending', 'Pending'), ('Refunded', 'Refunded'), ('Fraud', 'Fraud'), ('Other', 'Other')], max_length=128, null=True)),
                ('note', models.TextField()),
                ('will_pay_amount_cents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.IntegerField(default=0, null=True)),
                ('user_limit', models.IntegerField(default=0, null=True)),
                ('remaining', models.IntegerField(default=0, null=True)),
                ('description', models.TextField()),
                ('requires_shipping', models.BooleanField(default=False)),
                ('url', models.URLField(max_length=2048, null=True)),
                ('patron_count', models.IntegerField(default=0)),
                ('post_count', models.IntegerField(default=0)),
                ('discord_role_ids', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=1024)),
                ('image_url', models.URLField(max_length=2048, null=True)),
                ('published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(null=True)),
                ('unpublished_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tier',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Campaign'),
        ),
    ]
